# Generated by Django 5.0 on 2024-01-02 11:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("productmanagement", "0010_product_variant"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ProductVariant",
        ),
    ]
