# Generated by Django 5.0 on 2024-01-02 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productmanagement', '0011_delete_productvariant'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product_Variant',
            new_name='ProductVariant',
        ),
    ]
