# Generated by Django 5.0 on 2024-01-02 12:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("productmanagement", "0012_rename_product_variant_productvariant"),
    ]

    operations = [
        migrations.AddField(
            model_name="productvariant",
            name="color",
            field=models.CharField(
                blank=True, default="white", max_length=20, null=True
            ),
        ),
    ]
