# Generated by Django 5.0 on 2023-12-20 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categorymanagement', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='Brand_name',
            new_name='brand_name',
        ),
    ]
