# Generated by Django 5.0 on 2023-12-20 10:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("categorymanagement", "0002_rename_brand_name_brand_brand_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="brand",
            name="is_listed",
            field=models.BooleanField(default=True),
        ),
    ]
