# Generated by Django 5.0 on 2024-01-23 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_customuser_dob_customuser_gender_customuser_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='referal_code',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
