# Generated by Django 5.0 on 2024-01-24 06:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0005_customuser_referal_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="datejoined",
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="first_name",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="last_name",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
