# Generated by Django 5.0 on 2023-12-28 10:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order_management", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_mode",
            field=models.CharField(default="hi", max_length=20),
            preserve_default=False,
        ),
    ]
