# Generated by Django 5.0 on 2023-12-31 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0005_alter_orderproducts_delivery_date'),
        ('productmanagement', '0008_alter_product_discount_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproducts',
            name='product_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='productmanagement.product'),
        ),
    ]
