# Generated by Django 5.0 on 2024-01-04 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0008_remove_orderproducts_product_id_and_more'),
        ('productmanagement', '0013_productvariant_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproducts',
            name='size',
            field=models.IntegerField(default=7),
        ),
        migrations.AlterField(
            model_name='orderproducts',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='productmanagement.productvariant'),
        ),
    ]
