# Generated by Django 5.0 on 2024-01-06 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0011_orderproducts_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproducts',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
