# Generated by Django 5.0 on 2024-01-24 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0006_alter_customuser_datejoined_alter_customuser_email_and_more"),
        (
            "order_management",
            "0018_rename_coupen_applied_order_coupon_applied_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Returns",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reason", models.TextField(blank=True, null=True)),
                ("request_date", models.DateField(auto_now_add=True, null=True)),
                ("return_date", models.DateField(blank=True, null=True)),
                (
                    "order",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="order_management.orderproducts",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="home.customuser",
                    ),
                ),
            ],
        ),
    ]
