# Generated by Django 5.0 on 2023-12-26 16:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0002_cart_sub_total"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
