# Generated by Django 5.0 on 2024-01-04 04:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0007_remove_cart_product_id_remove_wishlist_product_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="size",
            field=models.CharField(default=7, max_length=20),
        ),
    ]
