# Generated by Django 5.0 on 2024-01-04 10:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0008_cart_size"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="size",
            field=models.CharField(max_length=20),
        ),
    ]
