# Generated by Django 5.0 on 2024-01-04 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0010_remove_wishlist_product_wishlist_product_id'),
        ('productmanagement', '0013_productvariant_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='product_id',
            field=models.ForeignKey(default=27, null=True, on_delete=django.db.models.deletion.SET_NULL, to='productmanagement.product'),
        ),
    ]
