# Generated by Django 5.0 on 2024-01-18 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0014_checkout_coupon_checkout_coupon_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='discount_amount',
            field=models.FloatField(null=True),
        ),
    ]
