# Generated by Django 5.0 on 2024-01-19 04:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0015_checkout_discount_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="checkout",
            name="discount_amount",
            field=models.FloatField(default=0, null=True),
        ),
    ]
