# Generated by Django 5.0 on 2024-01-19 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0016_alter_checkout_discount_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='product',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='size',
        ),
    ]
