# Generated by Django 5.0 on 2024-01-23 11:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0017_remove_checkout_product_remove_checkout_size"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="checkout",
            name="quantity",
        ),
        migrations.RemoveField(
            model_name="wishlist",
            name="stock",
        ),
    ]
