# Generated by Django 5.0 on 2024-01-22 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0006_productreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='created_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
